name = "magic-portfolio"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".worker-next/index.mjs"

assets = { directory = ".vercel/output/static", binding = "STATIC_ASSETS" }

pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "a45cefdc503c49dca1622038a46483f9"